"""empty message

Revision ID: 0bd59dd52e09
Revises: 9980b843ad7f
Create Date: 2020-07-13 11:45:23.469460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd59dd52e09'
down_revision = '9980b843ad7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###
