"""empty message

Revision ID: 26288d365092
Revises: 812c2a0af5c7
Create Date: 2020-07-13 00:35:21.967028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26288d365092'
down_revision = '812c2a0af5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'description')
    # ### end Alembic commands ###
