"""empty message

Revision ID: 649f834e714b
Revises: abb9e995b6ea
Create Date: 2020-07-12 16:55:20.869882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649f834e714b'
down_revision = 'abb9e995b6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
