"""empty message

Revision ID: 812c2a0af5c7
Revises: 6ac7207309a5
Create Date: 2020-07-12 23:37:00.434182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c2a0af5c7'
down_revision = '6ac7207309a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
