"""empty message

Revision ID: d41c65ac3674
Revises: 26288d365092
Create Date: 2020-07-13 02:06:13.124388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41c65ac3674'
down_revision = '26288d365092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'pitch_review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('pitch_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
